### ISSUE TITLE
The FaaS testing module of the TESTING_TOOL must have a graphic user interface

### ISSUE THREAD

**Issue by avanhoorn** [radon-h2020/radon-ctt#29]
From D2.1 (Companion)

ID | R-T.3.3-14 
------------ | -------------
Section | WP3: Methodology and Quality Assurance Requirements
Type| USABILITY
User Story | As a QoS Engineer, I want to be able to specify tests using a GUI.
Requirement | The FaaS testing module of the TESTING_TOOL must have a graphic user interface.
Extended Description | The FaaS module of the TESTING_TOOL must graphically provide information about the generated tests, as well as the input data and state of the infrastructure, which will be used. 
Priority | Must have
Affected Tools | TESTING_TOOL
Means of Verification | Tests and demos
Dependency | N/A

**Comment by avanhoorn** [comment]
Removed the M18 milestone. I am not sure where it came from. We agreed that CTT will not be part of the IDE for M18 (alpha).

**Comment by gcasale** [comment]
Approved

**Comment by avanhoorn** [comment]
Achieved through the CTT IDE plugin, as reported in D3.5.

**Comment by gcasale** [comment]
Approved
