### ISSUE TITLE
The data pipeline testing module of the TESTING_TOOL should support user configurable data production profiles

### ISSUE THREAD

**Issue by avanhoorn** [radon-h2020/radon-ctt#31]
From D2.1 (Companion)

ID | R-T3.3-2
------------ | -------------
Section | WP3: Methodology and Quality Assurance Requirements
Type| FUNCTIONAL_SUITABILITY
User Story | As a QoS Engineer, I want to be able to define custom data production profiles, based on which load testing data will be generated.
Requirement | The data pipeline testing module of the TESTING_TOOL should support user configurable data production profiles. 
Extended Description | Data production profiles define what type and format data needs to be generated and to specify what is the profile of generated data flow.
Priority | Should have
Affected Tools | TESTING_TOOL
Means of Verification | Using test case data production profiles for generating data into data pipeline and verifying that the produced data matches the profile.
Dependency | N/A

**Comment by avanhoorn** [comment]
@pjakovits Could you set the milestone, please?

**Comment by pjakovits** [comment]
> @pjakovits Could you set the milestone, please?

Please assign  milestone M24 to this issue @avanhoorn

**Comment by pjakovits** [comment]
The requirement is now achieved by incorporating CTT test agents (JMeter and DataPipeline agents) for load/performance testing. Users can modify the velocity of data generation, type of data objects that are injected and duration of the test (in the case of NiFi based Data Pipeline Agent). 

@gcasale please approve closing this requirement.

**Comment by gcasale** [comment]
Approved
