### ISSUE TITLE
The data pipeline testing module of the TESTING_TOOL should be able to ingest and analyze log data of the data pipeline under test to generate performance metrics for the deployed data pipeline

### ISSUE THREAD

**Issue by avanhoorn** [radon-h2020/radon-ctt#33]
From D2.1 (Companion)

ID | R-T3.3-4
------------ | -------------
Section | WP3: Methodology and Quality Assurance Requirements
Type| FUNCTIONAL_SUITABILITY
User Story | As a QoS Engineer, I want the testing tool to generate performance metrics for the data pipeline under testing.
Requirement | The data pipeline testing module of the TESTING_TOOL should be able to ingest and analyze log data of the data pipeline under test to generate performance metrics for the deployed data pipeline.
Extended Description | The goal is to parse and process the log data to generate performance metrics (e.g. latency/delay, error rate, dropped packets), which are required for evaluating the quality of the data pipeline.
Priority | Should have
Affected Tools | TESTING_TOOL
Means of Verification | Tests with different data pipeline test cases to verify that the log data was parsed correctly.
Dependency | R-T5.1-3

**Comment by pjakovits** [comment]
Should be closed as the requirement was changed to remove need to ingest and parse the logs, which can be handled by the monitoring component instead. New issue: #74 
@avanhoorn
