### ISSUE TITLE
The data pipeline testing module of the TESTING_TOOL could be able to display graphical representation of performance metrics.

### ISSUE THREAD

**Issue by avanhoorn** [radon-h2020/radon-ctt#34]
From D2.1 (Companion)

ID | R-T3.3-5
------------ | -------------
Section | WP3: Methodology and Quality Assurance Requirements Type| USABILITY
User Story | As a QoS Engineer, I want to see the visualization of the computed performance metrics.
Requirement | The data pipeline testing module of the TESTING_TOOL could be able to display graphical representation of performance metrics.
Extended Description | The goal is to have visual graphs generated from the log data for each of the performance metrics.
Priority | Could have
Affected Tools | TESTING_TOOL
Means of Verification | Tests with different data pipeline test cases to verify that graphs have been generated correctly
Dependency | N/A

**Comment by pjakovits** [comment]
We have decided to drop this requirement for the CTT tool, as the visualization scope is outside the actual testing process and the priority of the requirement is low (Could have). Reasons for dropping the requirement is also addressed in D2.2 - Final requirements. 

@gcasale please approve.

**Comment by gcasale** [comment]
I thought more about this and ok to drop if there is a discussion on the rationale in D2.2.

**Comment by pjakovits** [comment]
Ok.
@avanhoorn can you please close this issue as dropping the requirement R-T3.3-5 has been approved.
