### ISSUE TITLE
It could be useful if users can configure upper and lower bounds in the data pipeline testing module of the TESTING_TOOL for the performance metrics that are computed

### ISSUE THREAD

**Issue by avanhoorn** [radon-h2020/radon-ctt#35]
From D2.1 (Companion)

ID | R-T3.3-6
------------ | -------------
Section | WP3: Methodology and Quality Assurance Requirements
Type| FUNCTIONAL_SUITABILITY
User Story | As a QoS Engineer, I want to be able to configure critical lower and upper bounds of performance metrics and visualize them.
Requirement | It could be useful if users can configure upper and lower bounds in the data pipeline testing module of the TESTING_TOOL for the performance metrics that are computed.
Extended Description | Specifying upper and lower bounds for performance metrics could be used for defining visual alerts that indicate when the data pipeline under test is performing supoptimal to the desired performance.
Priority | Could have
Affected Tools | TESTING_TOOL
Means of Verification |  Tests with different data pipeline test cases and production profiles to verify that the tool recognises when upper and lower bounds of peformance metrics have been reached
Dependency | N/A

**Comment by pjakovits** [comment]
We have decided to drop this requirement for the CTT tool, as the visualization scope is outside the actual testing process and the priority of the requirement is low (Could have). Reasons for dropping the requirement is also addressed in D2.2 - Final requirements. 

@gcasale please approve.

**Comment by gcasale** [comment]
I would prefer to reject it, could have requirements are optional and so there is no harm in leaving it in the list as it may influence long term development of the tool.

**Comment by avanhoorn** [comment]
@pjakovits Could you set the milestone, please?

**Comment by pjakovits** [comment]
The requirement is achieved, User is able to define which `performance_metric` is to be tracked inside the `radon.policies.testing.DataPipelineLoadTest` RADON policy (https://github.com/radon-h2020/radon-particles/tree/master/policytypes/radon.policies.testing/DataPipelineLoadTest) and also define `lower_bound` and `upper_bound` values for it inside the policy. 

@gcasale please approve closing this requirement

**Comment by gcasale** [comment]
Approved
