### ISSUE TITLE
It could be useful for the data pipeline testing module of the TESTING_TOOL to have a graphical user interface for configuring tests and displaying test results.

### ISSUE THREAD

**Issue by avanhoorn** [radon-h2020/radon-ctt#36]
From D2.1 (Companion)

ID | R-T3.3-7
------------ | -------------
Section | WP3: Methodology and Quality Assurance Requirements
Type| USABILITY
User Story | As a QoS Engineer, I want to be able to use a graphical user interface for configuring the tool and displaying generated metrics and visualizations.
Requirement | It could be useful for the data pipeline testing module of the TESTING_TOOL to have a graphical user interface for configuring tests and displaying test results.
Extended Description | The goal is to provide a more user friendly interface for configuring tests and displaying results
Priority | Could have
Affected Tools | TESTING_TOOL
Means of Verification | Tests with different data pipeline test cases to verify that all nessesary information is displayed correctly on the user interface.
Dependency | N/A

**Comment by avanhoorn** [comment]
@pjakovits Could you set the milestone, please?

**Comment by pjakovits** [comment]
> @pjakovits Could you set the milestone, please?

Please assign  milestone M27 to this issue @avanhoorn

**Comment by pjakovits** [comment]
The requirement is achieved by allowing users to define test parameters (using TOSCA policy) in the RADON Graphical Modelling Tool and displaying the performance metrics through Grafana.

@gcasale please approve closing this requirement.

**Comment by gcasale** [comment]
Approved
