### ISSUE TITLE
It could be useful for the data pipeline testing module of the TESTING_TOOL to support running multiple different tests in a sequence on the same data pipeline.   

### ISSUE THREAD

**Issue by avanhoorn** [radon-h2020/radon-ctt#37]
From D2.1 (Companion)

ID | R-T3.3-8
------------ | -------------
Section | WP3: Methodology and Quality Assurance Requirements
Type| USABILITY
User Story | As a QoS Engineer, I want to be able to configure a set of different data production profiles that will be checked/evaluated in a sequence in an automated manner.
Requirement | It could be useful for the data pipeline testing module of the TESTING_TOOL to support running multiple different tests in a sequence on the same data pipeline.  
Extended Description | The goal is to support running a sequence of performance tests without requiring user intervention.
Priority | Could have
Affected Tools | TESTING_TOOL
Means of Verification | Tests with a prepared set of testing configurations on different data pipelines to verify that all tests were run successfully
Dependency | R-T5.4-1 (using the RADON Orchestrator data pipeline plugins to deploy and control data pipelines under testing)

**Comment by pjakovits** [comment]
The requirement is was achieved by the CTT Execution of multiple tests feature # and injecting loads through JMeter and Nifi pipeline with different datasets. 
It was reported in Deliverable D3.5  – Continuous testing tool II (31-March-2021 ) -  https://radon-h2020.eu/wp-content/uploads/2021/09/D3.5-Continuous-testing-tool-II.pdf
