### ISSUE TITLE
Less or equal 10% error on data velocity/volume

### ISSUE THREAD

**Issue by avanhoorn** [radon-h2020/radon-ctt#42]
From D6.1:

Also, we expect the CTT to have at most ten percent (≤10%) of error on reproducing data velocity and volume with respect to three or more (≥3) benchmark workloads. The benchmark workloads could comprise Google Cluster Traces, Clarknet Traces, and loads generated using stochastic models. The stochastic models generate the loads by estimating the probability distribution of potential outcomes by allowing for random variation in one or more multiple parameters over a timestamp. Here, we will use different queueing models which are already used in QT tool or some other deterministic modeling for generating loads by varying multiple input parameters, especially for performance evaluating data pipelines.

**Comment by avanhoorn** [comment]
@pjakovits Could you set the milestone, please?

**Comment by pjakovits** [comment]
> @pjakovits Could you set the milestone, please?

Please assign  milestone M27 to this issue @avanhoorn

**Comment by pjakovits** [comment]
This KPI was addressed by verifying that RADON orchestrated Data pipeline have 100% success rate on data velocity and volume with respect to three different datasets, namely image datasets, Twitter dataset and Sensor dataset over two demo applications, i.e., Thumbnail generation with data pipeline and File Transferred between different Cloud Storage demo applications. Refer to this deliverable.

It was reported in Deliverable D6.5 – Final Assessment Report (30-June-2021) - https://radon-h2020.eu/wp-content/uploads/2021/09/D6.5-Final-Assessment-Report.pdf
