### ISSUE TITLE
Support release of demo video

### ISSUE THREAD

**Issue by duelle** [radon-h2020/radon-ctt#56]
The demo video should be released within the next days. To do so, we need to provide the details to the responsible person.

**Comment by avanhoorn** [comment]
Once it's available, we could also link it in our README file and the one from the methodology.

**Comment by duelle** [comment]
I just provided the link to the video to the responsible person. Now waiting for a reply whether there is anything else we need to provide.

**Comment by avanhoorn** [comment]
The video is published (https://youtu.be/35VN2edyvsc) and a link is included in our README.
