### ISSUE TITLE
Can not build the CTT server docker container

### ISSUE THREAD

**Issue by pjakovits** [radon-h2020/radon-ctt#63]
OpenAPI generated server Docker container build command fails. 

The command:
`docker build -t openapi_server .`
fails with error:
 `unable to execute 'gcc': No such file or directory`

Suggested fix is to change the Dockerfile and replace the line:

`RUN pip3 install --no-cache-dir -r requirements.txt`

with:
```
RUN apk --update add python py-pip openssl ca-certificates py-openssl wget git
RUN apk --update add --virtual build-dependencies libffi-dev openssl-dev python-dev py-pip build-base \
  && pip install --upgrade pip \
  && pip install -r requirements.txt \
  && apk del build-dependencies
```

**Comment by pjakovits** [comment]
Also created a pull request with a potential tested solution: https://github.com/radon-h2020/radon-ctt/pull/64

**Comment by duelle** [comment]
Hi @pjakovits,
thanks for bringing this up and providing a PR #64 
The existing Dockerfile was auto-generated by the OpenAPI stub generator and was missing some of the dependencies that we added in our implementation but did not include in the Dockerfile yet.

I checked your PR and it works good for me. Therefor, closing this ticket and moving over to the PR.
