### ISSUE TITLE
Installation issues

### ISSUE THREAD

**Issue by gcasale** [radon-h2020/radon-ctt#71]
Gives apt-get install commands for these:
"For CTT users, the following software must be installed:
For CTT developers, the following additional software must be installed:"

In particular, for virtualenv or otherwise it goes ahead installing without.

My installation dies immediatley with this error:
--
> data/radon-ctt$ ./radon_ctt_start.sh

Already using interpreter /usr/bin/python3
Using base prefix '/usr'
New python executable in /data/radon-ctt/ctt-server/.venv/bin/python3
Not overwriting existing python script /data/radon-ctt/ctt-server/.venv/bin/python (you must use /data/radon-ctt/ctt-server/.venv/bin/python3)
Installing setuptools, pkg_resources, pip, wheel...done.
Ignoring connexion: markers 'python_version >= "3.6"' don't match your environment
Ignoring connexion: markers 'python_version == "3.4"' don't match your environment
Ignoring connexion: markers 'python_version <= "2.7"' don't match your environment
Requirement already satisfied: connexion>=2.3.0 in ./.venv/lib/python3.5/site-packages (from -r requirements.txt (line 2)) (2.5.0)
Requirement already satisfied: swagger-ui-bundle>=0.0.2 in ./.venv/lib/python3.5/site-packages (from -r requirements.txt (line 5)) (0.0.6)
Requirement already satisfied: python_dateutil>=2.6.0 in ./.venv/lib/python3.5/site-packages (from -r requirements.txt (line 6)) (2.8.1)
Requirement already satisfied: setuptools>=21.0.0 in ./.venv/lib/python3.5/site-packages (from -r requirements.txt (line 7)) (46.4.0)
Requirement already satisfied: gitpython in ./.venv/lib/python3.5/site-packages (from -r requirements.txt (line 8)) (3.1.2)
Requirement already satisfied: sqlalchemy in ./.venv/lib/python3.5/site-packages (from -r requirements.txt (line 9)) (1.3.17)
Requirement already satisfied: marshmallow in ./.venv/lib/python3.5/site-packages (from -r requirements.txt (line 10)) (3.6.0)
Requirement already satisfied: opera in ./.venv/lib/python3.5/site-packages (from -r requirements.txt (line 11)) (0.5.7)
Requirement already satisfied: flask>=1.0.4 in ./.venv/lib/python3.5/site-packages (from connexion>=2.3.0->-r requirements.txt (line 2)) (1.1.2)
Requirement already satisfied: inflection>=0.3.1 in ./.venv/lib/python3.5/site-packages (from connexion>=2.3.0->-r requirements.txt (line 2)) (0.4.0)
Requirement already satisfied: PyYAML>=5.1 in ./.venv/lib/python3.5/site-packages (from connexion>=2.3.0->-r requirements.txt (line 2)) (5.3.1)
Requirement already satisfied: requests>=2.9.1 in ./.venv/lib/python3.5/site-packages (from connexion>=2.3.0->-r requirements.txt (line 2)) (2.23.0)
Requirement already satisfied: jsonschema>=2.5.1 in ./.venv/lib/python3.5/site-packages (from connexion>=2.3.0->-r requirements.txt (line 2)) (3.2.0)
Requirement already satisfied: clickclick>=1.2 in ./.venv/lib/python3.5/site-packages (from connexion>=2.3.0->-r requirements.txt (line 2)) (1.2.2)
Requirement already satisfied: openapi-spec-validator>=0.2.4 in ./.venv/lib/python3.5/site-packages (from connexion>=2.3.0->-r requirements.txt (line 2)) (0.2.8)
Requirement already satisfied: Jinja2>=2.0 in ./.venv/lib/python3.5/site-packages (from swagger-ui-bundle>=0.0.2->-r requirements.txt (line 5)) (2.11.2)
Requirement already satisfied: six>=1.5 in ./.venv/lib/python3.5/site-packages (from python_dateutil>=2.6.0->-r requirements.txt (line 6)) (1.14.0)
Requirement already satisfied: gitdb<5,>=4.0.1 in ./.venv/lib/python3.5/site-packages (from gitpython->-r requirements.txt (line 8)) (4.0.5)
Requirement already satisfied: ansible>=2.8 in ./.venv/lib/python3.5/site-packages (from opera->-r requirements.txt (line 11)) (2.9.9)
Requirement already satisfied: itsdangerous>=0.24 in ./.venv/lib/python3.5/site-packages (from flask>=1.0.4->connexion>=2.3.0->-r requirements.txt (line 2)) (1.1.0)
Requirement already satisfied: Werkzeug>=0.15 in ./.venv/lib/python3.5/site-packages (from flask>=1.0.4->connexion>=2.3.0->-r requirements.txt (line 2)) (1.0.1)
Requirement already satisfied: click>=5.1 in ./.venv/lib/python3.5/site-packages (from flask>=1.0.4->connexion>=2.3.0->-r requirements.txt (line 2)) (7.1.2)
Requirement already satisfied: chardet<4,>=3.0.2 in ./.venv/lib/python3.5/site-packages (from requests>=2.9.1->connexion>=2.3.0->-r requirements.txt (line 2)) (3.0.4)
Requirement already satisfied: certifi>=2017.4.17 in ./.venv/lib/python3.5/site-packages (from requests>=2.9.1->connexion>=2.3.0->-r requirements.txt (line 2)) (2020.4.5.1)
Requirement already satisfied: idna<3,>=2.5 in ./.venv/lib/python3.5/site-packages (from requests>=2.9.1->connexion>=2.3.0->-r requirements.txt (line 2)) (2.9)
Requirement already satisfied: urllib3!=1.25.0,!=1.25.1,<1.26,>=1.21.1 in ./.venv/lib/python3.5/site-packages (from requests>=2.9.1->connexion>=2.3.0->-r requirements.txt (line 2)) (1.25.9)
Requirement already satisfied: importlib-metadata; python_version < "3.8" in ./.venv/lib/python3.5/site-packages (from jsonschema>=2.5.1->connexion>=2.3.0->-r requirements.txt (line 2)) (1.6.0)
Requirement already satisfied: attrs>=17.4.0 in ./.venv/lib/python3.5/site-packages (from jsonschema>=2.5.1->connexion>=2.3.0->-r requirements.txt (line 2)) (19.3.0)
Requirement already satisfied: pyrsistent>=0.14.0 in ./.venv/lib/python3.5/site-packages (from jsonschema>=2.5.1->connexion>=2.3.0->-r requirements.txt (line 2)) (0.16.0)
Requirement already satisfied: MarkupSafe>=0.23 in ./.venv/lib/python3.5/site-packages (from Jinja2>=2.0->swagger-ui-bundle>=0.0.2->-r requirements.txt (line 5)) (1.1.1)
Requirement already satisfied: smmap<4,>=3.0.1 in ./.venv/lib/python3.5/site-packages (from gitdb<5,>=4.0.1->gitpython->-r requirements.txt (line 8)) (3.0.4)
Requirement already satisfied: cryptography in ./.venv/lib/python3.5/site-packages (from ansible>=2.8->opera->-r requirements.txt (line 11)) (2.9.2)
Requirement already satisfied: zipp>=0.5 in ./.venv/lib/python3.5/site-packages (from importlib-metadata; python_version < "3.8"->jsonschema>=2.5.1->connexion>=2.3.0->-r requirements.txt (line 2)) (1.2.0)
Requirement already satisfied: cffi!=1.11.3,>=1.8 in ./.venv/lib/python3.5/site-packages (from cryptography->ansible>=2.8->opera->-r requirements.txt (line 11)) (1.14.0)
Requirement already satisfied: pycparser in ./.venv/lib/python3.5/site-packages (from cffi!=1.11.3,>=1.8->cryptography->ansible>=2.8->opera->-r requirements.txt (line 11)) (2.20)
Traceback (most recent call last):
  File "/usr/lib/python3.5/runpy.py", line 184, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/lib/python3.5/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/data/radon-ctt/ctt-server/openapi_server/__main__.py", line 25, in <module>
    main()
  File "/data/radon-ctt/ctt-server/openapi_server/__main__.py", line 14, in main
    init_db()
  File "/data/radon-ctt/ctt-server/db_orm/database.py", line 23, in init_db
    from models import project, testartifact, deployment, execution, result
  File "/data/radon-ctt/ctt-server/models/project.py", line 21
    uuid: str
        ^
SyntaxError: invalid syntax

**Comment by duelle** [comment]
Hi @gcasale,
today we pushed an update and also mentioned the packages required for Ubuntu in the `README`.
A more detailed `Getting Started` documentation can be found here: https://continuous-testing-tool.readthedocs.io/en/latest/#getting-started

Currently, there are two modes of operation:
* (recommended) Docker-based execution where the CTT server itself is executed inside a Docker container and other deployments are instantiated 'next to it' with the Docker engine. This mode of operation does only require the Docker packages mentioned in the requirements.
* Native execution where the CTT server runs directly on the host machine and only the deployments are instantiated with Docker.

If you are experiencing any issues with the updated version, please let us know.

**Comment by gcasale** [comment]
Thanks. I have tried to run the sequence of commands in Docker in the RTD. The tests seemed to work fine. There were though multiple exceptions showing up in the docker containers output, some seemed 500 HTTP return code. I can try again, but since the overall outcome seemed successful I wanted to check if this is expected or not.

**Comment by duelle** [comment]
Thanks for the feedback.
We do not expect HTTP 500 to occur, though there might be scenarios where they could occur. This could be the case in the 'create execution' step when the deployment is not completely finished (e.g., Docker containers of SockShop are not up and fully started yet) or in the 'create results' step when the execution did not finish yet.
For further investigation, it would be great if you could provide us more detail on when you experienced the HTTP 500 errors.

**Comment by duelle** [comment]
In case the issue persists, please reopen this ticket with more details on the details of the failure.
