### ISSUE TITLE
The FaaS testing module of the TESTING_TOOL should have a command line interface

### ISSUE THREAD

**Issue by avanhoorn** [radon-h2020/radon-ctt#73]
From D2.1 (Companion)

ID | R-T.3.3-15
------------ | -------------
Section | WP3: Methodology and Quality Assurance Requirements
Type| USABILITY
User Story | As a QoS Engineer, I want to be able to specify tests using CLI.
Requirement | The FaaS testing module of the TESTING_TOOL should have a command line interface. 
Extended Description | A CLI can be used to specify test execution. Furthermore, a CLI can be useful to display, e.g., to display raw results, in a format parsable by other tools and applications (e.g., CSV, XML, JSON).
Priority | Should have
Affected Tools | TESTING_TOOL
Means of Verification | Tests and demos
Dependency | N/A

**Comment by avanhoorn** [comment]
There was an error in the level of compliance, which we corrected. @gcasale

**Comment by gcasale** [comment]
OK

**Comment by avanhoorn** [comment]
Achieved through CTT's CLI tool, as reported in D3.5.

**Comment by gcasale** [comment]
Approved
