### ISSUE TITLE
The data pipeline testing module of the TESTING_TOOL should be able to analyze log data of the data pipeline under test to generate performance metrics

### ISSUE THREAD

**Issue by pjakovits** [radon-h2020/radon-ctt#74]
| ID | R-T3.3-4 |
| ------------- | ------------- |
| Section|	WP3: Methodology and Quality Assurance Requirements|
|Type|	FUNCTIONAL_SUITABILITY|
|User Story|	As a QoS Engineer, I want the testing tool to generate performance metrics for the data pipeline under testing.|
|Requirement|	The data pipeline testing module of the TESTING_TOOL should be able to analyze log data of the data pipeline under test to generate performance metrics. |
|Extended Description |	The goal is to analyse log data to generate performance metrics (e.g. latency/delay, error rate, dropped packets), which are required for evaluating the quality of the data pipelines.|
|Priority|	Should have|
Affected Tools|	TESTING_TOOL|
|Means of Verification|	Tests with different data pipeline test cases to verify that the performance metrics are generated correctly. |
|Dependency|R-T5.1-3|

**Comment by pjakovits** [comment]
@gcasale please approve.

**Comment by gcasale** [comment]
Approved.

**Comment by avanhoorn** [comment]
@pjakovits Could you set the milestone, please?

**Comment by pjakovits** [comment]
Please assign  milestone M22 to this issue @avanhoorn

**Comment by pjakovits** [comment]
This requirement was achieved by utilizing Jmeter and Prometheus (together NiFi PrometheusReportingTask to expose metrics) to collect metrics and CTT data pipeline plugin. 
It was reported in Deliverable D3.5 – Continuous testing tool II (31-March-2021 ) - https://radon-h2020.eu/wp-content/uploads/2021/09/D3.5-Continuous-testing-tool-II.pdf
