### ISSUE TITLE
CTT demo not reproducible 

### ISSUE THREAD

**Issue by AlexSpart** [radon-h2020/radon-ctt#80]
Can't succeed to reproduce the demo example found on https://continuous-testing-tool.readthedocs.io/en/latest/ (deploying locally the SockShop repo -https://github.com/radon-h2020/demo-ctt-sockshop.git\) 
The problem occurs after "Generating Artifacts" step.

CTT image:
radonconsortium/radon-ctt:latest
DIGEST:sha256:8e792336f1ca18eadd246e406cfdfe3eb67c1820eb7762354c6ae83439f70328

CTT container log:
```
INFO:werkzeug: * Running on http://0.0.0.0:18080/ (Press CTRL+C to quit)
INFO:__main__:Created directory path /tmp/RadonCTT/project/3910f791-d6a1-4ec1-af03-5b906b2eda1d
INFO:__main__:Cloning repository https://github.com/radon-h2020/demo-ctt-sockshop.git into /tmp/RadonCTT/project/3910f791-d6a1-4ec1-af03-5b906b2eda1d
INFO:__main__:Project created: <Project '3910f791-d6a1-4ec1-af03-5b906b2eda1d', 'SockShop', 'https://github.com/radon-h2020/demo-ctt-sockshop.git', 'project/3910f791-d6a1-4ec1-af03-5b906b2eda1d'>
INFO:werkzeug:172.17.0.1 - - [11/Sep/2020 14:46:26] "POST /RadonCTT/project HTTP/1.1" 200 -
INFO:__main__:Plugin 'radon.policies.testing.JMeterLoadTest' found.
INFO:__main__:Plugin 'radon.policies.testing.HttpEndpointTest' found.
INFO:__main__:Could not find matching plugin for radon.policies.testing.PingTest.
INFO:__main__:The policy-defined TI blueprint (radon.blueprints.testing.DeploymentTestAgent) does not match the TI model (radon.blueprints.testing.JMeterMasterOnly).
INFO:__main__:Created test artifact for radon.blueprints.testing.JMeterMasterOnly.
INFO:werkzeug:172.17.0.1 - - [11/Sep/2020 14:46:53] "POST /RadonCTT/testartifact HTTP/1.1" 200 -
```

**Comment by duelle** [comment]
Hi @AlexSpart, thanks for reporting this. Could you please try to run the example with `radonconsortium/radon-ctt:dev` instead of `radonconsortium/radon-ctt:latest` to see whether the dev-version already has the issue resolved?

**Comment by AlexSpart** [comment]
Hi @duelle, thank you for taking on this, ` radonconsortium/radon-ctt:dev` gives me the same error log.

**Comment by duelle** [comment]
I had a first try to reproduce your issue with the `radonconsortium/radon-ctt:dev` container, but unfortunately could not reproduce any problems by going through the docs. Furthermore, I could not spot any issues in the log snippet you provided. 

Could you please elaborate on the issue you are having? Any error message or broken functionality?

**Comment by AlexSpart** [comment]
Hi @duelle, 
I had another run (deploying ImageResize demo on my AWS platform)with both the new latest`(DIGEST:sha256:08f5f73aacc262a77a871cdb6fbe266fe50084fb9a390cc06b7ea34f61c7502f)`
 & 
dev `(DIGEST:sha256:08f5f73aacc262a77a871cdb6fbe266fe50084fb9a390cc06b7ea34f61c7502f)` 
versions of radonconsortium/radon-ctt tool and it seems to work flawlessly. 

Thanks
