### ISSUE TITLE
The data pipeline testing module of the TESTING_TOOL must be able to set up synthetic stream data generation for data pipelines under test

### ISSUE THREAD

**Issue by pjakovits** [radon-h2020/radon-ctt#83]
| ID | R-T3.3-3 |
| ------------- | ------------- |
| Section|	WP3: Methodology and Quality Assurance Requirements|
|Type|	FUNCTIONAL_SUITABILITY|
|User Story|	As a QoS Engineer, I want synthetic data stream to be generated and provided as input to the data pipeline under test    |
|Requirement|	The data pipeline testing module of the TESTING_TOOL must be able to set up synthetic stream data generation for data pipelines under test. |
|Extended Description |	The goal is to mock the input streams of data pipelines by generating synthetic data for performance testing the user defined data pipelines.  |
|Priority|	Must have |
Affected Tools|	TESTING_TOOL|
|Means of Verification | Tests with different demo data pipelines and predefined data production profiles to verify that the correct structure of synthetic data is being generated and data pipeline behaves as expected. |
|Dependency|N/A|

**Comment by pjakovits** [comment]
Please approve @gcasale

**Comment by pjakovits** [comment]
This requirement is fulfilled by two different CTT testing agents:

- DataPipeline testing agent, where NiFi pipelines are used to generate synthetic data. Respective node type:   https://github.com/radon-h2020/radon-particles/tree/master/nodetypes/radon.nodes.testing/DataPipeline
- JMeter testing agent, where JMeter test-plans can be used to generate synthetic data. Respective node type:  https://github.com/radon-h2020/radon-particles/tree/master/nodetypes/radon.nodes.testing/JMeter

@gcasale Please approve closing this requirement

**Comment by gcasale** [comment]
Approved
